//Metodos de usuarios
POST http://localhost:3000/usuario/add HTTP/1.1
Content-Type: application/json

{
    "id_usuario":2,
    "nombreDeUsuario":"Saul",
    "contrasena":"123456",
    "grupo":"b"
}

###
GET http://localhost:3000/usuario/ HTTP/1.1

###
GET http://localhost:3000/usuario/buscar/Michel&123456 HTTP/1.1

###
DELETE http://localhost:3000/usuario/delete/2 HTTP/1.1

###
PUT http://localhost:3000/usuario/update/1 HTTP/1.1
Content-Type: application/json

{
    "nombreDeUsuario":"Jose Alberto",
    "contrasena": "joalmoso123"
}

//Metodos chat

###
GET http://localhost:3000/chat/ HTTP/1.1

###
POST http://localhost:3000/chat/add HTTP/1.1
Content-Type: application/json

{
    "id_usuario":2,
    "Contenido":"Saul mampo",
    "Emisor":"Saul",
    "Destinatario":"Michi"
}

// Tareas

###
POST  http://localhost:3000/tareas/add HTTP/1.1
Content-Type: application/json

{
    "id_usuario":2,
    "Titulo":"Tarea sistemas digitales",
    "Fecha":"01/19/2024",
    "Grado":"1",
    "Contenido":"Reporte de proyecto 2"
}

###
GET http://localhost:3000/tareas/ HTTP/1.1